# Initial coin filtering options
PRICE_CHANGE_THRESHOLD: 25.0  # Minimum percentage price change (absolute)
PRICE_RANGE_VOLATILITY_THRESHOLD: 0.15  # Minimum range volatility in %

# Technical indicator parameters
TREND_INDICATORS:
  SMA_WINDOW: 14  # Window for Simple Moving Average
  EMA_WINDOW: 14  # Window for Exponential Moving Average
  MACD:
    SHORT_WINDOW: 12  # Short window for MACD calculation
    LONG_WINDOW: 26   # Long window for MACD calculation
    SIGNAL_WINDOW: 9  # Signal window for MACD calculation
  ICHIMOKU:
    TENKAN_WINDOW: 9  # Window for Tenkan-sen (Conversion Line)
    KIJUN_WINDOW: 26  # Window for Kijun-sen (Base Line)
    SENKOU_B_WINDOW: 52  # Window for Senkou Span B (Leading Span B)
    SENKOU_SHIFT: 26  # Forward shift for Senkou spans

# Momentum indicator parameters
MOMENTUM_INDICATORS:
  RSI_WINDOW: 14  # Window for Relative Strength Index
  STOCHASTIC:
    WINDOW: 14  # Window for the Stochastic Oscillator
    SMOOTH_WINDOW: 3  # Smoothing window for %K line
  WILLIAMS_R_WINDOW: 14  # Window for Williams %R calculation
  CCI_WINDOW: 20  # Window for Commodity Channel Index

# Volatility indicator parameters
VOLATILITY_INDICATORS:
  BOLLINGER_BANDS:
    WINDOW: 20  # Window for Bollinger Bands
    NUM_STD_DEV: 2  # Number of standard deviations for bandwidth
  ATR_WINDOW: 14  # Window for Average True Range calculation

# Strategy
MAX_COIN_ALLOCATION: 0.20  # Maximum portfolio allocation per coin in %
BUY_CONDITION: 20 # Score needed to buy a coin
SELL_CONDITION: 10 # Score needed to sell a coin

# Order execution
ORDER_VALUE: 10.0 # Order value for the transactions
TAKE_PROFIT_DELTA: 700 # Take profit in base points
STOP_LOSS_DELTA: 500 # Stop loss in base points


